export const QR_CONFIG = {
  ARRIVAL_WINDOW_OPEN_MINUTES: 30,
  ARRIVAL_WINDOW_CLOSE_MINUTES: 30,
  BREAK_WINDOW_OPEN_MINUTES: 15,
  BREAK_WINDOW_CLOSE_MINUTES: 15,
  DEPARTURE_WINDOW_OPEN_MINUTES: 30,
  DEPARTURE_WINDOW_CLOSE_MINUTES: 15,
  TOKEN_BYTES: 32,
} as const
